# Generated by Django 2.1.2 on 2018-10-20 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messagetyping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-id',), 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='messagelike',
            options={'ordering': ('-id',), 'verbose_name': 'Message like', 'verbose_name_plural': 'Message likes'},
        ),
        migrations.AlterModelOptions(
            name='messagetyping',
            options={'ordering': ('-id',), 'verbose_name': 'Message typing', 'verbose_name_plural': 'Message typings'},
        ),
    ]
